name: Update .pre-commit-config.yaml

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  update-pre-commit-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.14'
          cache: "pip"

      - name: Install pre-commit
        run: pip install --upgrade pre-commit

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update .pre-commit-config.yaml
        run: pre-commit autoupdate --freeze

      - name: Check for changes
        id: changes
        run: |
          git add .pre-commit-config.yaml
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          commit-message: "chore(deps): Update .pre-commit-config.yaml"
          title: "chore(deps): Update .pre-commit-config.yaml"
          body: "Automated update of .pre-commit-config.yaml via scheduled workflow."
          branch: "update/pre-commit-config-yaml"
          base: ${{ github.ref_name }}
          labels: "update"
          reviewers: "linuxdaemon"
          assignees: "linuxdaemon"
          sign-commits: true
